import "./globals.css";

export const metadata = {
  title: "Voltenindonesia",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.ico", 
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
