import "./globals.css";

export const metadata = {
  title: "Voltenindonesia",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icon.ico", 
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/icon.ico" sizes="any" />
      </head>
      <body >
        {children}
      </body>
    </html>
  );
}
